language: python
python: 2.7
addons:
  apt:
    packages:
      - lftp
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - graphviz
env:
  global:
    - "FTP_USER=travis"
    - secure: "N+WU26//t0zlT8yYmeAenIHtlOucpD0sTXMEV/cAndobCGNI5AvIgPoGSzG/sMGkdai6m+CeEXCrmRrWpZp3qLxocROB1MRSiKDOEf3uhI2aLQ8LNG8qMYWHonmcQjW/W504Yex653b0i9HZBtYM1ZfqNcuiVnJYGuAUUTX4La5IUv2M8vbWZjqYrvmZjymripHb+nfWbnzGaIchN1/8ntsuQvQe6hj7R2EQdcw1do8IpxZKlyPgRxAPeoJ+UwCvuaH6jS2YfL+VTN9ixTzz/G/QRCrjSGvZ+uuvyCqwYcqR6ycglaU86pUVPtceT4FkuYlS6/SjsNVjbWDJha1GWMIxStD6Jy5wchPdeLV8Mct42vTzZ6PzroogIIcRCXGr0XIoNOoWpgjfN7x5qdGLp0O3f1Q9PYmONLp/w6pD+1V9CFvTkA2BmgHfOsk9pfZx5JfC7T8yKA78dbTum8aeZv7EAu6VxJO9yboVyOGnsHnoNHmgA0vrQdaOUJG17qICGFHs/Q8/V89g9eU+fwazKmyzzwylO7eyL8FiVGHvo0PqvsXOwVjSWCov+LQqQZZQARsv6hSKeluN4pyL6kAmgzlvxwUOi3oXRvlkW0MbSnMKQnR8L53uG/iX6hmlMf8NbPm85g2H9hbHnOcpLP2EP3MbKj/5r999cnDk/cjJdwY="
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
before_install:
  - pip install --upgrade pip
install:
  - pip install --upgrade sphinx sphinxcontrib-httpdomain
script:
  cd docs && make html latexpdf && cd ..
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && cd docs/_build/
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && lftp -u $FTP_USER,$FTP_PASSWORD -p 20002 sftp://77.66.8.130:20002/gatewayapi_front/ -e "mirror --parallel=10 -p -R html docs; cd docs; put latex/gatewayapi.pdf; exit"
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && lftp -u $FTP_USER,$FTP_PASSWORD -p 20002 sftp://77.66.8.131:20002/gatewayapi_front/ -e "mirror --parallel=10 -p -R html docs; cd docs; put latex/gatewayapi.pdf; exit"
notifications:
  slack:
    secure: "AwvNpeRvbRgxWIV7ZuhvPQ80OlGrLAdWmra2yryPZ/tq8sd7ftSsi7IpFpsigpYeYzoNmVyFQs576QLA9QtIJGGoNvGNFwaClUZTy1V9WXxXO3+3ScStE22DbxFEr3g5U3iJDz/ycFYxo5TTHvK0vPTaZmRB5jctAiEw548m8X0joWYyGveVk4MuKz7+zXBR9HoKPr48JiYEgCgBk/CCeAZJK7fRPg5fm6anaYTHPsnvIQ6mbCvqF49EAcjYZlEhQgl+jhVdidG1gpMS1DE3pkgvQY4SB5cQDX0LY78KT/xkBALgolH00/nbbJsgG5lfBGLgeEY3xlLq2Uiccbo80h9zXFbk9S+vg89WcX3mUK803WAWi89spBhRKIpP2OVTOtqXCzsWldVOAIExbLntKKJd3pUEUSDB/yLA0asq0GfiuBnagrdBUPuP5qFdqUfrppYF9g18NYlt3Y6rMlKOQRyckPCQ6mhDA/0uUfdKk7Whv1P+gg0t9HVy50gZnREKZHCsRm5B/enG8pTmkwY/FlVv9NtGFvYTfGfDZ3T0ibHWTkDehPWOmCgUblHCppIsopLGL/lm+MfsGLgNKrw7WNnDfp7FEeeazBiELo/3CMcY+GGR3oP3nKlKppXbO5/MYKjSvIC5aKXlarqFgcwhajr7JBfIEGUZ6BVLkC9y2fs="
  email: false
