language: python
python: 2.7
addons:
  apt:
    packages:
      - lftp
cache:
  - pip
  - apt
before_install:
  - pip install --upgrade pip
install:
  - pip install --upgrade sphinx sphinxcontrib-httpdomain
script:
  cd docs && make html

