steps:
- name: 'eu.gcr.io/gatewayapi-212008/sphinx'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'cd docs && make html latexpdf'
  waitFor: ['-'] # The '-' indicates that this step begins immediately.
  id: builder

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - >-
    docker build
    -t eu.gcr.io/gatewayapi-212008/docs:$BRANCH_NAME$TAG_NAME-$SHORT_SHA
    -t eu.gcr.io/gatewayapi-212008/docs:$BRANCH_NAME$TAG_NAME
    .
  waitFor: ['builder']
  id: runner

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - >-
    if [ "$BRANCH_NAME" == "master" ] || [ "$TAG_NAME" ] ; then
      docker push eu.gcr.io/gatewayapi-212008/docs:$BRANCH_NAME$TAG_NAME-$SHORT_SHA;
    fi
  waitFor: ['runner']
  id: push

  #- name: 'gcr.io/cloud-builders/kubectl'
  #  entrypoint: 'bash'
  #  args:
  #  - '-c'
  #  - >-
  #    if [ "$BRANCH_NAME" != "master" ] || [ "$TAG_NAME" ] ; then
  #      /builder/kubectl.bash set image deployment/web-app web-app=eu.gcr.io/gatewayapi-212008/gatewayapi-com:$BRANCH_NAME$TAG_NAME-$SHORT_SHA --namespace gwapi;
  #    fi
  #  env:
  #    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
  #    - 'CLOUDSDK_CONTAINER_CLUSTER=gatewayapi-stage'
  #  waitFor: ['push']
images:
- eu.gcr.io/gatewayapi-212008/docs:$BRANCH_NAME$TAG_NAME-$SHORT_SHA
- eu.gcr.io/gatewayapi-212008/docs:$BRANCH_NAME$TAG_NAME  
