apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: gwapi
  labels:
    app: docs
spec:
  replicas: 2
  selector:
    matchLabels:
        app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: eu.gcr.io/gatewayapi-212008/docs:master
        imagePullPolicy: Always
        env:
        - name: NGINX_HOST
          valueFrom:
            configMapKeyRef:
              name: docs-configmap
              key: Host
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 600m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: docs 
  namespace: gwapi
  labels:
    app: docs
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: docs 
